---
title: "compmusic"
author: "fenk"
date: "Spring 2021"
output: html_document
---
```{r}
library(tidyverse)
library(spotifyr)
```

```{r}
test <- get_playlist_audio_features("","37i9dQZF1DX8C9xQcOrE6T")
```
```{r}
ecm <- get_playlist_audio_features("", "37i9dQZF1DX8C9xQcOrE6T")
```

```{r}
test %>%
  summarise(
    mean_speechiness = mean(speechiness),
    mean_acousticness = mean(acousticness),
    mean_liveness = mean(liveness),
    sd_speechiness = sd(speechiness),
    sd_acousticness = sd(acousticness),
    sd_liveness = sd(liveness),
    median_speechiness = median(speechiness),
    median_acousticness = median(acousticness),
    median_liveness = median(liveness),
    mad_speechiness = mad(speechiness),
    mad_acousticness = mad(acousticness),
    mad_liveness = mad(liveness)
  )
```
```{r}
ecm %>%
  summarise(
    mean_speechiness = mean(speechiness),
    mean_acousticness = mean(acousticness),
    mean_liveness = mean(liveness),
    sd_speechiness = sd(speechiness),
    sd_acousticness = sd(acousticness),
    sd_liveness = sd(liveness),
    median_speechiness = median(speechiness),
    median_acousticness = median(acousticness),
    median_liveness = median(liveness),
    mad_speechiness = mad(speechiness),
    mad_acousticness = mad(acousticness),
    mad_liveness = mad(liveness)
  )
```

```{r}
zeros <- get_playlist_audio_features("", "6dv5FbNRVlQelteqnNDFTe")
seventies <- get_playlist_audio_features("", "67zYW4wCQezR6AH8EuNZ1Q")
```

```{r}
zeros_summary <- zeros %>%
  summarise(
    mean_popularity = mean(track.popularity),
    mean_danceability = mean(danceability),
    mean_valence = mean(valence),
    mean_energy = mean(energy),
    mean_acousticness = mean(acousticness),
  )
```

```{r}
seventies_summary <- seventies %>%
  summarise(
    mean_popularity = mean(track.popularity),
    mean_danceability = mean(danceability),
    mean_valence = mean(valence),
    mean_energy = mean(energy),
    mean_acousticness = mean(acousticness),
  )
```

```{r}
together <-
  bind_rows(
    zeros %>% mutate(category = "00s"),
    seventies %>% mutate(category = "70s")
  )
```

```{r}
zeros %>% ggplot(aes(x = energy)) + geom_histogram(binwidth = 0.1)
```
```{r}
together %>%                    # Start with awards.
  mutate(
    mode = ifelse(mode == 0, "Minor", "Major")
  ) %>%
  ggplot(                     # Set up the plot.
    aes(
      x = valence,
      y = energy,
      size = loudness,
      colour = mode
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(size = 0.1) +      # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    aes(
      x = valence,
      y = energy,
      label = label
    ),
    data = 
      tibble(
        label = c("Altijd wel iemand", "ENERGY"),
        category = c("zeros", "seventies"),
        valence = c(0.090, 0.123),
        energy = c(0.101, 0.967)
      ),
    colour = "black",         # Override colour (not mode here).
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "bottom",         # Align bottom of label with the point.
    nudge_x = -0.05,          # Nudge the label slightly left.
    nudge_y = 0.02            # Nudge the label slightly up.
  ) +
  facet_wrap(~category) +     # Separate charts per playlist.
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),   # Use grid-lines for quadrants only.
    minor_breaks = NULL       # Remove 'minor' grid-lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(0, 1),
    breaks = c(0, 0.50, 1),
    minor_breaks = NULL
  ) +
  scale_colour_brewer(        # Use the Color Brewer to choose a palette.
    type = "qual",            # Qualitative set.
    palette = "Paired"        # Name of the palette is 'Paired'.
  ) +
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud.
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Valence",
    y = "Energy",
    colour = "Mode"
  )
```


